HeadNode: 
  CustomActions: 
    OnNodeConfigured: 
      Script: "s3://devin-hpcscripts1234/run-on-headnode.sh"
  Iam: 
    S3Access: 
      - BucketName: devin-hpcscripts1234
  InstanceType: r6i.large 
  Networking: 
    AdditionalSecurityGroups: 
      - sg-0ebc93e160de95498
    SubnetId: subnet-05b2495f54b720cd4
  Ssh: 
    KeyName: devin.pastoor 
  LocalStorage:
    RootVolume:
      Size: 100 
Image: 
  Os: ubuntu2004
  CustomAmi: ami-061dc152260bb8d04
Region: us-east-2
Scheduling: 
  Scheduler: slurm
  SlurmQueues: 
    - Name: all 
      ComputeResources: 
        - Name: rstudio
          InstanceType: m6i.2xlarge
          MaxCount: 5
          MinCount: 0 
          Name: rstudio
      CustomActions: 
        OnNodeConfigured: 
          Script: "s3://devin-hpcscripts1234/install-compute.sh" 
      Iam: 
        S3Access: 
          - BucketName: devin-hpcscripts1234
      Networking: 
        SubnetIds: 
          - subnet-05b2495f54b720cd4
    - Name: memory 
      ComputeResources: 
        - Name: memory
          InstanceType: r6i.8xlarge
          MaxCount: 5
          MinCount: 0 
      CustomActions: 
        OnNodeConfigured: 
          Script: "s3://devin-hpcscripts1234/install-compute.sh" 
      Iam: 
        S3Access: 
          - BucketName: devin-hpcscripts1234
      Networking: 
        SubnetIds: 
          - subnet-05b2495f54b720cd4
    - Name: compute
      ComputeResources:
        - Name: compute
          InstanceType: c6i.4xlarge
          MaxCount: 5
          MinCount: 0
      CustomActions:
        OnNodeConfigured:
          Script: "s3://devin-hpcscripts1234/install-compute.sh"
      Iam:
        S3Access:
          - BucketName: devin-hpcscripts1234
      Networking:
        PlacementGroup:
          Enabled: TRUE
        SubnetIds: 
          - subnet-05b2495f54b720cd4
    - Name: gpu 
      ComputeResources:
        - Name: gpu 
          InstanceType: p3.2xlarge 
          MaxCount: 5
          MinCount: 0
          Name: gpu
      CustomActions:
        OnNodeConfigured:
          Script: "s3://devin-hpcscripts1234/install-compute.sh"
      Iam:
        S3Access:
          - BucketName: devin-hpcscripts1234
      Networking:
        PlacementGroup:
          Enabled: TRUE
        SubnetIds: 
          - subnet-05b2495f54b720cd4

Tags:
  - Key: rs:environment
    Value: development
  - Key: rs:owner
    Value: devin.pastoor@rstudio.com
  - Key: rs:project
    Value: solutions 
